### ISSUE TITLE
ortho_dl.sh not working 

### ISSUE THREAD

**Issue by Ruiqi-CUB** [jsoghigian/orthoset_construction#1]
Hi there! Thanks for developing such awesome tools!
I am trying to use ortho_dl.sh but it doesn't work. OrthDB has been updated, I am trying to update URLs but it still doesn't work. Would you mind updating the scripts? Thanks!

**Comment by jsoghigian** [comment]
Thanks for your interest in our tool! I'll take a look this week and get back to you soon.

**Comment by jsoghigian** [comment]
Hi @Ruiqi-CUB , could you test ortho_dl.sh ? In my limited tests on a couple of taxonomic levels it appears fixed. 

edit: I also updated ortho_process to work with the new taxa list from Ortho DB.  I'll update documentation but make sure you also grab the odb11 species list before running ortho_process!
